### ISSUE TITLE
Could not find location of package

### ISSUE THREAD

**Issue by krishnaff** [PEM--/fview-bksurfaceimage#1]
Hello,

Tried adding the package and running, but this is the error I get:
   Building the application                  \
Ensure dependencies...
 Famono:  Warning, could not find location of package "pierreeric:fview-bksurfaceimage"
   Building the application                  |

Any workaround please? 

Thanks!

**Comment by PEM--** [comment]
Hi @insaneinc01, How did you import the package? Did you clone the example or did you use the tutorial?

Normally, you should use it this [way](https://github.com/PEM--/fview-bksurfaceimage/blob/master/README.md#usage):

``` bash
meteor add pierreeric:fview-bksurfaceimage
```

**Comment by krishnaff** [comment]
Hello Pierre,
I did it just the standard way - 
`meteor add pierreeric:fview-bksurfaceimage.`
Meteor says:
`pierreeric:fview-bksurfaceimage  added, version 0.1.2`

But when I run the project with 'meteor' command, this is when I get the error:
`Famono:  Warning, could not find location of package "pierreeric:fview-bksurfaceimage"`

I'm running Meteor 1.0.2. Is it due to that by any chance? 

Thanks!

**Comment by PEM--** [comment]
Sounds like something has changed in Meteor-1.0.2 that prevents Famono from analyzing the requirejs dependencies. I got the same error as you. I've just switched to mjn:famous for the moment.
