### ISSUE TITLE
Error: No template='' specified

### ISSUE THREAD

**Issue by gam-ragnar** [PEM--/fview-bksurfaceimage#2]
I keep getting **Error: No template='' specified**
when I use jade but works fine for spacebar. 

```
+StateModifier
    +Modifier leftImageModifier
        +BkImageSurface leftImage

+BkImageSurface sizemode='ASPECTFILL' positionmode='BOTTOM' content='https://raw.githubusercontent.com/PEM--/fview-bksurfaceimage/master/doc/bkimagesurface.png' 
```

You guys have convinced me to join the jade camp and I can't stand html anymore.  How to make this work?

**Comment by PEM--** [comment]
:smile: This request for help just entered the TOP 10! I love the reason for it.

Just add an empty content:

``` jade
+BkImageSurface leftImage
  | 
```

Watch out the empty space after the pipe.

You can also check out the example: https://github.com/PEM--/fview-bksurfaceimage/blob/master/example/client/main.jade#L24
